### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/WhatsNearby#12]
## Tasks

- [ ] Update release notes
- [ ] Update README.md
- [ ] Update version number
- [ ] Create tag
- [ ] Update `semantic-mediawiki.org`
  - [ ] Run `composer update`
  - [ ] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter

@mwjames I guess we just forgot to release?

**Comment by JeroenDeDauw** [comment]
@mwjames any reason to not release version 1.0?

**Comment by kghbln** [comment]
@mwjames What about getting this out to the public officially?

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/WhatsNearby/pull/19

**Comment by mwjames** [comment]
Probably want to add `extension.json` but not this weekend.

**Comment by kghbln** [comment]
> Probably want to add extension.json but not this weekend.

Fair enough.

**Comment by krabina** [comment]
Regarding a version 1.0 - is it correct, that the current version is not working with maps 7.x?

This is what happens in my test:
 mediawiki/whats-nearby 1.x-dev requires mediawiki/maps ~3.5|~4.0|~5.0 -> satisfiable by mediawiki/maps[3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.8.1, 3.8.2, 3.8.x-dev, 4.0.0, 4.0.0-RC1, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.1.0, 4.2.0, 4.2.1, 4.3.0, 4.4.0, 5.0.0, 5.0.1, 5.0.2, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.6.0] but these conflict with your requirements or minimum-stability.

**Comment by kghbln** [comment]
> Regarding a version 1.0 - is it correct, that the current version is not working with maps 7.x?

Affirmative.

**Comment by mwjames** [comment]
> mediawiki/whats-nearby 1.x-dev requires mediawiki/maps ~3.5|~4.0|~5.0 -> satisfiable by mediawiki/maps[3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.8.1, 3.8.2, 3.8.x-dev, 4.0.0, 4.0.0-RC1, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.1.0, 4.2.0, 4.2.1, 4.3.0, 4.4.0, 5.0.0, 5.0.1, 5.0.2, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.6.0] but these conflict with your requirements or minimum-stability.

People, don't wait on me to get active, if you think something needs adjustment such as the range of `mediawiki/maps` being supported then send a PR and fix it.

**Comment by kghbln** [comment]
> such as the range of mediawiki/maps being supported 

I believe it is not just the range but also some other breaking issue which I have apparently not reported. Not sure why. :(

**Comment by JeroenDeDauw** [comment]
https://github.com/SemanticMediaWiki/WhatsNearby/pull/22
